CREATE TABLE challenges
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT REFERENCES app_user(id) NOT NULL ,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    solution        TEXT,
    difficulty      VARCHAR(50),
    category        VARCHAR(100),
    attachment_url  VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE app_user ADD COLUMN total_challenge_points INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS public."app_user" ALTER COLUMN total_challenge_points SET NOT NULL;