CREATE TABLE app_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role        VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    username    VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE
);